config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :rooms
  devise_for :users,
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                               :registrations => 'registrations'
                              },
             :path => '',
             :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}

  root "static#home"

  get '/auth/facebook/callback' => 'sessions#create'

  resources :users, only: [:show]

  resources :rooms do
    resources :reservations, only: [:new, :create, :index, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :rooms
  has_many :users, through: :rooms
  validates :name, presence: true
  validates :country, presence: true

  def self.country_list
    City.pluck(:country).uniq
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :start_date, :presence => {:message => "Must have a check in date." }, uniqueness: :true
  validates_datetime :end_date, :after => :start_date, message: "Checkout must be after checkin date."
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :city
  has_many :reservations

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :capacity, presence: true
  validates :bed_rooms, presence: true
  validates :bath_rooms, presence: true
  validates :listing_name, presence: true, length: {maximum: 30}
  validates :summary, presence: true
  validates :address, presence: true, length: {maximum: 100}
  validates :price, presence: true

  def city_attributes=(city)
    self.city = City.find_or_create_by(name: city[:name])
    self.city.update(city)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :rooms
  has_many :cities, through: :rooms
  has_many :reservations
  validates :username, presence: true, length: {maximum: 30}

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

  protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
     devise_parameter_sanitizer.permit(:account_update, keys: [:username, :description, :password, :email])
   end


end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  private

  def city_params
    params.require(:city).permit(:name, :country)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show]
  before_action :authenticate_user!

  def create
    @reservation = current_user.reservations.new(reservation_params)
    if @reservation.save
      redirect_to @reservation.room, notice: "Your reservation has been made!"
    else
      redirect_to new_room_reservation_path(@reservation.room)
    end
  end

  def new
    @room = Room.find(params[:room_id])
  end

  def index
    @room = Room.find(params[:room_id])
    @reservations = @room.reservations
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def show

  end

  def new
    @room = current_user.rooms.build
    @room.build_city
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to @room, notice: "Room succesfully created."
    else
      render :new, alert: "Please provide all information for this room."
    end
  end

  def edit

  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: "Room succesfully updated."
    else
      render :edit, alert: "Please provide all information for this room."
    end
  end

  private

  def room_params
    params.require(:room).permit(:home_type, :room_type, :capacity, :bed_rooms, :bath_rooms, :listing_name, :summary, :address, :price, :active, city_attributes: [:name, :country])
  end

  def set_room
    @room = Room.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_by(:uid => auth['uid']) do |u|
      u.username = auth['info']['name']
      u.email = auth['info']['email']
    end
    session[:user_id] = user.id
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :authenticate_user!

  def home
    @rooms = Room.all
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authtentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show

  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def listing_link(room)
    content_tag(:a, "#{room.city.name}, #{room.city.country} - #{room.listing_name} - #{room.summary}", href: room_path(room))
  end
end

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error", class: "text-center" ) if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice", class: "text-center" ) if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert", class: "text-center" ) if flash[:alert]  %>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Nomadbnb</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">

            <% if !user_signed_in? %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% else %>
              <li><%= link_to "Become a Host", new_room_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile page", user_path(current_user) %></li>
                  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                  <li><%= link_to "Your rooms", rooms_path %></li>
                  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% end %>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NomadBnbRailsProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reservations/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        Create a new reservation
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4 form-group">
          <%= form_for([@room, @room.reservations.new]) do |f| %>

            <label>Check in</label>
            <%= f.date_field :start_date, class: "form-control" %></br>

            <label>Check out</label>
            <%= f.date_field :end_date, class: "form-control" %></br>

            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :price, value: @room.price %>
            </br>
            <%= f.submit "Book Now", class: "btn btn-primary" %>
          <% end %>
       </div>
      </div>
    </div>
</div>

app/views/reservations/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Reservations", rooms_path, class: "sidebar-link active"%></li>

    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Reservations for <%= @room.listing_name %>
      </div>
      <div class="panel-body">
        <% @reservations.each_with_index do |reservation, index| %>
          <div class="row">
            <div class="col-md-9">
              <h4><%= index + 1 %> - Check in: <%=reservation.start_date.to_date%> / Check out: <%=reservation.end_date.to_date%></h4>
            </div>
            <div class="col-md-3"></div>

          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/reservations/new.html.erb
<%= render 'form' %>

app/views/rooms/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        Create a new room
    </div>
    <div class="panel-body">
        <div class="container">
            <%= form_for @room, html: {multipart: true}  do |f| %>

            <div class="row">

                <div class="col-md-4 select nopadding">
                    <div class="form-group">
                        <label>Property Type</label>
                        <%= f.select :home_type, [["Apartment", "Apartment"], ["House","House"],["Bed & Breakfast","Bed & Breakfast"]], id: "home_type", prompt: "Select", class: "form-control" %>
                    </div>
                </div>

                <div class="col-md-4 select">
                    <div class="form-group">
                        <label>Room Type</label>
                        <%= f.select :room_type, [["Entire", "Entire"], ["Private","Private"],["Shared","Shared"] ], id: "room_type", prompt: "Select", class: "form-control" %>
                    </div>
                </div>

                <div class="col-md-4 select">
                    <div class="form-group">
                        <label>Accommodates</label>
                        <%= f.select :capacity, [["1 guest", 1], ["2 guests", 2], ["3 guests", 3], ["4 guests", 4], ["5 guests", 5], ["6+ guests", 6]], id: "capacity", prompt: "Select", class: "form-control" %>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-md-4 select nopadding">
                    <div class="form-group">
                        <label>Bedrooms</label>
                        <%= f.select :bed_rooms, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: 'Select', class: 'form-control' %>
                    </div>
                </div>

                <div class="col-md-4 select">
                    <div class="form-group">
                        <label>Bathrooms</label>
                        <%= f.select :bath_rooms, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: 'Select', class: 'form-control' %>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label>Listing Name</label>
                    <%= f.text_field :listing_name, placeholder: 'Provide a descriptive name for your listing', class: 'form-control' %>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label>Summary</label>
                    <%= f.text_area :summary, rows: 5, placeholder: 'Write a brief summary about your new room', class: 'form-control' %>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label>Address</label>
                    <%= f.text_field :address, placeholder: 'What is your address?', class: 'form-control' %>
                </div>
            </div>

            <%= f.fields_for :city do |c| %>
            <div class="row">

                <div class="col-md-4 nopadding">
                    <div class="form-group">
                        <label>City</label>
                        <%= c.text_field :name, list: "cities_autocomplete", class: 'form-control', placeholder: 'City name' %>
                        <datalist id="cities_autocomplete">
                            <%= City.all.each do |city| %>
                            <option value="<%= city.name%>"></option>
                            <% end %>
                        </datalist>
                    </div>
                </div>

                <div class="col-md-4 nopadding">
                    <div class="form-group">
                        <label>Country</label>
                        <%= c.text_field :country, list: "countries_autocomplete", class: 'form-control', placeholder: 'Country name'%>
                        <datalist id="countries_autocomplete">
                            <%= City.country_list.each do |country| %>
                            <option value="<%=country%>"></option>
                            <% end %>
                        </datalist>
                    </div>
                </div>

            </div>

            <% end %>

            <div class="row">
                <div class="col-md-4 nopadding">
                    <div class="form-group">
                        <label>Nightly Price</label>
                        <div class="input-group">
                            <div class="input-group-addon">$</div>
                            <%= f.text_field :price, placeholder: 'e.g. $50', class: 'form-control' %>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <label><%= f.check_box :active %>Active</label>
                </div>
            </div>

            <div class="actions nopadding">
                <%= f.submit "Save", class: "btn btn-primary" %>
            </div>
            <% end %>

        </div>
    </div>
</div>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listing", rooms_path, class: "sidebar-link active"%></li>

    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">
        <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-9">
              <h4><%= link_to room.listing_name, room_path(room) %></h4>
            </div>
            <div class="col-md-3"></div>
              <%= link_to "Update", edit_room_path(room), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/rooms/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3 text-center">
            <%= @room.user.username %>
          </div>

          <div class="col-md-9">
            <h4><%= @room.listing_name %></h4>
            <%= @room.address %>

            <div class="row text-center row-space-1">
              <div class="col-sm-3">
                  <i class="fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                  <i class="fa fa-users fa-2x"></i>
              </div>
              <div class="col-sm-3">
                  <i class="fa fa-bed fa-2x"></i>
              </div>
              <div class="col-sm-3">
                  <i class="fa fa-ship fa-2x"></i>
              </div>
            </div>

            <div class="row text-center">
              <div class="col-sm-3">
                <%= @room.home_type %>
              </div>
              <div class="col-sm-3">
                <%= @room.capacity %>
                <%= @room.capacity > 1? "Guests" : "Guest" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bed_rooms %>
                <%= @room.bed_rooms > 1? "Bedrooms" : "Bedroom" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bath_rooms %>
                <%= @room.bath_rooms > 1? "Bathrooms" : "Bathroom" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </br>
    </br>
    <div class="row text-center">
        <%= link_to "Create new reservation", new_room_reservation_path(@room), class: "btn btn-primary"  %>
    </div>
    </br>
    <div class="row text-center">
        <%= link_to "See all reservations", room_reservations_path(@room), class: "btn btn-primary"  %>
    </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
      <div class="panel-default">
        <div class="panel-heading">Verified info</div>
        <div class="panel-body">
          Email Address
        </div>
      </div>
      <div class="panel-default">
        <div class="panel-heading">Connected accounts</div>
        <div class="panel-body">
          <% if @user.provider %>
            <%= @user.provider.capitalize %>
          <% else %>
            Manual sign up
          <% end %>
        </div>
      </div>
      <div class="panel-default">
        <div class="panel-heading">About me</div>
        <div class="panel-body">

        </div>
      </div>
  </div>
  <div class="col-md-6">
    <h2>Hey, I'm <%= @user.username %>!</h2>

    <div class="description row-space-3">
      <%= @user.description %>
    </div>
  </div>
</div>